program: /home/ahmedb/projects/project-phase-2/scripts/reps_tuning.py
method: bayes
# task_name: super_resolution
metric:
  goal: maximize
  name: psnr_all

parameters:
  sampler.sampler_config.lr:
    distribution: log_uniform_values
    min: 1.e-6
    max: 1.0

  sampler.sampler_config.lam:
    distribution: log_uniform_values
    min: 1.e-3
    max: 10
  sampler.sampler_config.num_iters:
    distribution: int_uniform
    min: 1
    max: 10

command:
  - ${env}
  - python
  - ${program}
  - project_name=deepspeech2
  - data=esc50-demo
  - sampler=reps
  - num_runs=1
  - save_samples=False
  - eval_fid=False
  - batch_size=10
  - ${args_no_hyphens}